name: 'Snyk Job Summary Action'
description: 'Add a Job Summary from Snyk reports, also uploads HTML reports to Github Packages'

inputs:
 dependencies-report-path:
   description: '' # todo
   required: false
 code-report-path:
   description: '' # todo
   required: false

runs:
  using: composite

  steps:
    - uses: actions/setup-node@v3

    - run: npm install snyk-to-html --location=global
      shell: bash

    - name: convert Snyk Dependencies json to html format
      run: snyk-to-html -i ${{inputs.dependencies-report-path}} -o snyk_dependencies.html
      shell: bash

    - name: convert Snyk Code json to html format
      run: snyk-to-html -i ${{inputs.code-report-path}} -o snyk_code.html
      shell: bash

    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v3
      with:
        name: snyk-details
        path: |
          snyk_dependencies.html
          snyk_code.html
        retention-days: 7
        if-no-files-found: ignore

    - run: pip install mdutils
      name: install mdutils
      shell: bash

    - name: Run script
      run: |
        INPUT_DEPENDENCIES_REPORT_PATH=${{inputs.dependencies-report-path}}
        INPUT_CODE_REPORT_PATH=${{inputs.code-report-path}}
        python ${{ github.action_path }}/job_summary.py
      shell: bash

    - name: Add output to Job Summary
      run: cat vulnerabilities.md >> $GITHUB_STEP_SUMMARY
      shell: bash
